services:
  app:
    build:
      context: .
      args:
        GOIMGVER: $GOIMGVER
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        GROUPNAME: $GROUPNAME
        WORKDIR: $WORKDIR
        AIRVER: $AIRVER
        
    extra_hosts:
      - host.docker.internal:host-gateway 
    ports:
      - $REQUESTPORT:8080
    tty: true
    working_dir: $WORKDIR
    environment:
      TZ: $TIMEZONE
      GOPROJNAME: $GOPROJNAME
    volumes:
      - ./:$WORKDIR
    entrypoint: >
      sh -c "
        bash entrypoint.sh
      "
